// eslint-disable-next-line import/no-anonymous-default-export
export default {
  hi: 'hi',
  general: {
    'load-fail': 'Failed to load product data. Please try again later.',
    update: 'Update',
    userUpdated: 'The user has been successfully updated',
    userUpdateFailed: 'An error occurred while trying to update the user.',
    "show-more": 'Show More',
    "show-less": "Show Less",
    "related-products": "Related Products"
  },
  'user-overview': {
    title: 'Personal Information',
    picture: 'Profile Picture',
  },
  form: {
    'first-name-label': 'First Name',
    'first-name-placeholder': 'Add first name',
    'last-name-label': 'Last Name',
    'last-name-placeholder': 'Add last name',
    'email-label': 'Email',
    'email-placeholder': 'Enter your email address',
    'password-label': 'Password',
    'password-placeholder': 'Enter your password',
    'new-password-label': 'New Password',
    'new-password-placeholder': 'Enter your new password',
    'repeat-new-password-label': 'Repeat new password',
    'repeat-new-password-placeholder': 'Repeat password',
    'change-password': 'Change Password',
    'current-password': 'Current Password',
    'update-password': 'Update Password',
    'current-password-label': 'Current Password',
    'current-password-placeholder': 'Enter your current password',
    'confirm-password': 'Confirm Password',
    'confirm-password-placeholder': 'Confirm your new password',
    'select-landing-label': 'Select Landing',
    'phone-number-label': 'Phone Number',
    'forgot-password': 'Forgot your password?',
    'create-password': 'Create password',
    'phone-number-placeholder': 'Add your phone number',
    'company-name-label': 'Company Name',
    'company-name-placeholder': 'Enter business name',
    'description-label': 'Description',
    'description-placeholder': 'Add description',
    'confirm-password-validation': 'Password must match',
    'login-validation': 'Invalid email or password',
    'display-name-label': 'Display Name',
  },
  signin: {
    title: 'Sign in to your account',
    form: {
      title: 'Sign in',
      email: {
        label: 'Email',
        placeholder: 'Add your email',
      },
      password: {
        label: 'Password',
        placeholder: 'Add your password',
      },
      submit: 'Login',
      noAccount: 'Don\'t have an account?',
      signUp: 'Sign up',
      forgotPassword: 'Forgot your password?',
      rememberMe: 'Remember me',
    },
  },
  register: {
    title: 'Create your account',
    form: {
      title: 'Sign up',
      firstname: {
        label: 'Firstname',
        placeholder: 'Add your firstname',
      },
      lastname: {
        label: 'Lastname',
        placeholder: 'Add your lastname',
      },
      email: {
        label: 'Email',
        placeholder: 'EJ: myexample@gmail.com',
      },
      password: {
        label: 'Enter Password',
        placeholder: 'Password',
      },
      passwordConfirmation: {
        label: 'Confirm Password',
        placeholder: 'Password',
      },
      submit: 'Sign up',
      haveAccount: 'Have an account?',
      signIn: 'Sign in',
    },
  },
  search: {
    title: 'Search',
    filters: 'FILTERS',
    sidebar: {
      year: 'Year',
      company: 'Company',
      price: 'Price',
    },
  },
};
